<div id="people" class="peopletxt">
<ul>
	<li class="bold"><?=$this->translate("Office");?></li>
	<li>Rua Marquês das Minas Nº5 R/c Dir.</li>
	<li>2750 - 433 CASCAIS</li>
	<li>Portugal</li>
</ul>
<ul>
	<li class="bold">Ana Sutherland</li>
	<li><a href="mailto:anasutherland@arch05.com">anasutherland@arch05.com</a></li>
	<li class="bold">Daniela Castelbranco</li>
	<li><a href="mailto:danielacastelbranco@arch05.com">danielacastelbranco@arch05.com</a></li>
	<li class="bold">Hugo Afonso</li>
	<li><?=$this->translate("mob:");?> +351 926 927 556</li>
	<li><a href="mailto:hugoafonso@arch05.com">hugoafonso@arch05.com</a></li>
	<li class="bold">Joana Netto </li>
	<li><a href="mailto:joanarogan@arch05.com">joanarogan@arch05.com</a></li>
	<li class="bold">Miguel Cordeiro</li>
	<li><?=$this->translate("mob:");?> +351 912 550 313</li>
	<li><a href="mailto:miguelcordeiro@arch05.com">miguelcordeiro@arch05.com</a></li>
</ul>

<div class="dash"></div>
<table class="table-home">
	<thead>
    <tr>
     <th><a href="/whoweare"><?=$this->translate('The team');?></a></th>
     <th><a href="/whatwedo"><?=$this->translate('Profile');?></a></th>
     <th><a href="">Blog</a></th>
     <th><a href="/projects/isaim">01</a></th>
     <th><a href="/projects/peroboi">02</a></th>
     <th><a href="/projects/boatshelter">03</a></th>
     <th><a href="/projects/palacete">04</a></th>
     <th><a href="/projects/building">05</a></th>
     <th><a href="/projects/flag">06</a></th>
     <th><a href="/projects/rogantable">07</a></th>
     <th><a href="/projects/restaurant">08</a></th>
     <th><a href="/projects/forum">09</a></th>
     <th><a href="/projects/lubango">10</a></th>
     <th><a href="/projects/alcantara">11</a></th>
     <th><a href="/projects/amadorabd">12</a></th>											
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td><a href="/whoweare"><?=$this->translate('Who we are');?></a></td>
      <td><a href="/whatwedo"><?=$this->translate('What we do');?></a></td>
      <td><a href="blog.arch05.com"><?=$this->translate('Cross to talk');?></a></td>
      <td><a href="/projects/isaim"><?=$this->translate('Toilets Macau');?></a></td>
      <td><a href="/projects/peroboi"><?=$this->translate('Pero Boi house');?></a></td>
      <td><a href="/projects/boatshelter"><?=$this->translate('Boat shelter');?></a></td>
      <td><a href="/projects/palacete"><?=$this->translate('Cruz da Pedra');?></a></td>
      <td><a href="/projects/building"><?=$this->translate('Office building');?></a></td>
      <td><a href="/projects/flag"><?=$this->translate('Computer center');?></a></td>
      <td><a href="/projects/rogantable"><?=$this->translate('Rogan Table');?></a></td>
      <td><a href="/projects/restaurant"><?=$this->translate('Marina rest.');?></a></td>
      <td><a href="/projects/forum"><?=$this->translate('Office Macau');?></a></td>
      <td><a href="/projects/lubango"><?=$this->translate('PDM Lubango');?></a></td>
      <td><a href="/projects/alcantara"><?=$this->translate('Alcantara LX');?></a></td>
      <td><a href="/projects/amadorabd"><?=$this->translate('Amadora BD 2003');?></a></td>
    </tr>
  </tfoot>
  <tbody>
    <tr class="front-images-links">
      <td><a href="/whoweare"><img src="/images/home/brain.jpg" alt="<?=$this->translate('Who we are');?>"/></a></td>
      <td><a href="/whatwedo"><img src="/images/home/What.jpg" alt="<?=$this->translate('What we do');?>"/></a></td>
      <td><a href="blog.arch05.com"><img src="/images/home/blog.jpg" alt="<?=$this->translate('Cross to talk');?>"/></a></td>
      <td><a href="/projects/isaim"><img src="/images/home/WC_02.jpg" alt="<?=$this->translate('Toilets Macau');?>"/></a></td>
      <td><a href="/projects/peroboi"><img src="/images/home/pero_boi.jpg" alt="<?=$this->translate('Pero Boi house');?>"/></a></td>
      <td><a href="/projects/boatshelter"><img src="/images/home/fire_boat.jpg" alt="<?=$this->translate('Boat shelter');?>"/></a></td>
      <td><a href="/projects/palacete"><img src="/images/home/palacete-logo.jpg" alt="<?=$this->translate('Cruz da Pedra');?>"/></a></td>
      <td><a href="/projects/building"><img src="/images/home/office_building.jpg" alt="<?=$this->translate('Office building');?>"/></a></td>
      <td><a href="/projects/flag"><img src="/images/home/flag.jpg" alt="<?=$this->translate('Computer center');?>"/></a></td>
      <td><a href="/projects/rogantable"><img src="/images/home/mesa_rogan.jpg" alt="<?=$this->translate('Rogan Table');?>"/></a></td>
      <td><a href="/projects/restaurant"><img src="/images/home/MARINA.jpg" alt="<?=$this->translate('Marina rest.');?>"/></a></td>
      <td><a href="/projects/forum"><img src="/images/home/FORUM.jpg" alt="<?=$this->translate('Office Macau');?>"/></a></td>
      <td><a href="/projects/lubango"><img src="/images/home/mascara.jpg" alt="<?=$this->translate('PDM Lubango');?>"/></a></td>
      <td><a href="/projects/alcantara"><img src="/images/home/alcantara.jpg" alt="<?=$this->translate('Alcantara LX');?>"/></a></td>
      <td><a href="/projects/amadorabd"><img src="/images/home/BD.jpg" alt="<?=$this->translate('Amadora BD 2003');?>"/></a></td>
    </tr>
  </tbody>
</table>
</div>
