<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?=$this->headTitle();?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?=$this->headMeta();?>
<?=$this->headLink();?>
<?=$this->headScript();?>
<?=$this->placeholder('js');?>
<?=$this->placeholder('scripts');?>
<?=$this->placeholder('css');?>
</head>
<body>
	<?php echo $this->layout()->content; ?>
</body>
</html>