<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?=$this->headTitle();?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?=$this->headMeta();?>
<?=$this->headLink();?>
<?=$this->headScript();?>
<?=$this->placeholder('js');?>
<?=$this->placeholder('scripts');?>
<?=$this->placeholder('css');?>
</head>
<body>
<div id="header"><p><a href="/locale/index/locale/pt_PT/0/default/1/1">pt</a> | <a href="/locale/index/locale/en_US/0/default/1/1">en</a></p></div>
<?php echo $this->layout()->content; ?>
</body>
</html>